# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='state',
            new_name='region',
        ),
        migrations.AddField(
            model_name='airport',
            name='country_iso',
            field=models.CharField(default='US', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airport',
            name='region_iso',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
