# Generated by Django 2.0.1 on 2018-03-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_auto_20171224_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='picture_link',
            field=models.URLField(blank=True),
        ),
    ]
