# Generated by Django 2.0.1 on 2018-09-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_flight_picture_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='years_only',
            field=models.BooleanField(default=False),
        ),
    ]
