# Generated by Django 2.1.7 on 2019-03-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_userprofile_years_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='flight',
            name='picture',
            field=models.ImageField(blank=True, upload_to='static/user_photos'),
        ),
    ]
