# Generated by Django 2.1.7 on 2019-04-02 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0009_auto_20190326_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='home_airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flights.Airport'),
        ),
    ]
